import type { FontDetails } from '../types/font.type'

/**
 * 폰트 더미 데이터
 * 실제 서비스에서는 API를 통해 가져옵니다.
 */
export const FONTS_DATA: readonly FontDetails[] = [
  {
    fontId: 1,
    fontName: '손글씨체',
    writerName: '김영희',
    example: '따뜻하고 전원적인 손글씨를 느낄 수 있는 글꼴입니다.',
    downloadCount: 15420,
    bookmarkCount: 892,
    isBookmarked: false,
    fontAddr: 'https://cdn.fontory.com/fonts/handwriting/손글씨체_v1.2.ttf',
  },
  {
    fontId: 2,
    fontName: '모던체',
    writerName: '이지훈',
    example: '깔끔하고 현대적인 느낌의 폰트로 비즈니스에 적합합니다.',
    downloadCount: 12870,
    bookmarkCount: 1056,
    isBookmarked: true,
    fontAddr: 'https://cdn.fontory.com/fonts/modern/모던체_pro_v2.0.otf',
  },
  {
    fontId: 3,
    fontName: '칼리그래피',
    writerName: '박선영',
    example: '아름다운 서체의 곡선이 돋보이는 예술적인 폰트',
    downloadCount: 9834,
    bookmarkCount: 654,
    isBookmarked: false,
    fontAddr: 'https://cdn.fontory.com/fonts/calligraphy/칼리그래피_elegant_v1.8.ttf',
  },
  {
    fontId: 4,
    fontName: '말랑말랑체',
    writerName: '정예린',
    example: '활기차고 사랑스러운 어린이용 글꼴입니다.',
    downloadCount: 18290,
    bookmarkCount: 1432,
    isBookmarked: true,
    fontAddr: 'https://cdn.fontory.com/fonts/kids/말랑말랑체_cute_v3.1.woff2',
  },
  {
    fontId: 5,
    fontName: '클래식체',
    writerName: '최민준',
    example: '전통적이고 고전적인 느낌의 매력적인 서체',
    downloadCount: 7456,
    bookmarkCount: 423,
    isBookmarked: false,
    fontAddr: 'https://cdn.fontory.com/fonts/classic/클래식체_serif_v1.5.ttf',
  },
  {
    fontId: 6,
    fontName: '포켓체',
    writerName: '강동원',
    example: '포켓같이 따뜻하고 소중한 우리의 이야기를 담았습니다.',
    downloadCount: 11203,
    bookmarkCount: 789,
    isBookmarked: false,
    fontAddr: 'https://cdn.fontory.com/fonts/story/포켓체_warm_v2.3.otf',
  },
  {
    fontId: 7,
    fontName: '비트체',
    writerName: '조성민',
    example: '디지털 시대에 어울리는 트렌디하고 세련된 서체입니다.',
    downloadCount: 8924,
    bookmarkCount: 567,
    isBookmarked: false,
    fontAddr: 'https://cdn.fontory.com/fonts/digital/비트체_tech_v1.0.woff2',
  },
  {
    fontId: 8,
    fontName: '꿈꼴체',
    writerName: '이예진',
    example: '꿈같이 아름다운 순간들을 담아낸 감성적인 폰트',
    downloadCount: 13456,
    bookmarkCount: 1098,
    isBookmarked: true,
    fontAddr: 'https://cdn.fontory.com/fonts/dream/꿈꼴체_fantasy_v2.7.ttf',
  },
] as const
